server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true

  datasource:
    url: jdbc:mysql://localhost:3306/store_reservation
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver