###
POST http://localhost:8080/reservation?storeName=store2
Authorization: Bearer

###
POST http://localhost:8080/reservation/cancel?storeName=store
Authorization: Bearer

###
GET http://localhost:8080/reservation/showList
Authorization: Bearer

###
POST http://localhost:8080/reservation/checkIn?storeName=store1
Authorization: Bearer

###
POST http://localhost:8080/reservation/checkOut?storeName=store1
Authorization: Bearer